pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JAVA_HOME"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                rem echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir("C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Demo-Pipeline\\java-maven-junit-helloworld-master") {
				echo "clean & install"
                bat "mvn clean install"
                }
            
            }
        }
     }
    post  {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '**/target/surefire-reports/TEST-*.xml'
      )
      }
   } 
}
