pipeline {
    agent any

    tools {
        maven "MAVEN_HOME"
        jdk "JAVA_HOME"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"                
            }
        }
        stage('Build') {
            steps {
                dir("C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Demo-Pipeline\\java-maven-junit-helloworld-master") {
				echo "clean & install"
                bat "mvn clean install"
				echo "%JAVA_HOME%"
                cd target
				%JAVA_HOME%\\bin\\java -cp java-maven-junit-helloworld-2.0-SNAPSHOT.jar com.example.javamavenjunithelloworld.HelloApp
				}
            }
        }
     }
    post  {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '**/target/surefire-reports/TEST-*.xml'
      )
      }
   } 
}
